apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-lister-binding
subjects:
- kind: ServiceAccount
  name: ns-reconciler-anthos-test-config-repo-sync-16
  namespace: config-management-system
roleRef:
  kind: ClusterRole
  name: deployment-lister
  apiGroup: rbac.authorization.k8s.io
