kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-viewer-san-data
rules:
- apiGroups: ["apps"]
  resources: ["pods", "services", "deployments"]
  resourceNames: ["anthos-test"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
